services:
  backend:
    build:
      context: ./
    ports:
      - "8080:8080"
    container_name: spring-app

  swagger:
    build:
      context: ./src/main/resources/static/swagger-ui
    ports:
      - "8081:80"
    container_name: swagger-ui
